# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1

# Builder stage: install dependencies and build TypeScript
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json tsconfig.json ./
COPY src ./src
RUN npm install --ignore-scripts && npm run build

# Final stage: runtime image
FROM node:lts-alpine AS runner
WORKDIR /app

# Copy built artifacts and dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Default command to start the MCP server
CMD ["node", "dist/index.js"]
